[google_service_account]
type = "service_account"
project_id = "decisive-design-450510-k3"
private_key_id = "86a8f265021e4928b7435bb8cf196f07f696c05a"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCp7q8uJAg20LDn
Z+swU5btYXwVu2rjmxCU2f6yZrGE4xWwqBklyjXSDj6Z796Gac2AxUdVLeplzIz1
EOSS4LoEASPDkqCib/UWy0ZzdwM8AYcrG/LBk+TkzfLpXufBKnsb7LTk3hpkl3hu
yB0BVJrFEE9nAQsQwq6T6hXTzkj2Wg/8nsFC5wXTc4q0j31cKNA9xlYUftmcOJ8Z
5ei05Sm5xuG/3zjI1KsVtAF9gwheR45LBfNKPO9qBRLAK2LJzxTD/aSJ+fivdYe9
DGext3qioTv+b9A+UQAR34ImRdpp5KKGRe1iEX7FxRThyxeQkMokhgbcqHw12nXN
QUuDqX6nAgMBAAECgf8gho8BReRMmaVCpaFenqFEzmPxxO2wov2JgDA/9WgFB3If
Xg1yLkIe8psI2+C72YR8IUaGB0PWOFDCl3koo9r26UDvLiGQ9dzzf/T8JMt5sNEu
bysH4kbthH36LTAuyPLHZYc6R0jF+DgU/DiRCKCXF4gbLxfvHVRM+4EyCUnt3P7Y
piqS0Hi1p8NDPsolrCN22U9y3xzxVsZhUnVFad4993CwKyjfHTyXbZFiQ28pGQYk
++j3eIazHxBa/JTaghnjWeReyo93A6FagkYVRnaIXr+FYrHDwnY3q8NLgETSzMyM
rZNYbUiMFKLRYrtGFlYRrxInBn8Htf+sYb9dRWECgYEA6WpmC9GlWdVj/Jvw/dpf
tuSmmJDnexUqJmxs7CY5pvfQ2GOjHCrbZKbz+BVnPdhVx7mup5P9smKmjUe8u/q3
9p8M7QLtPmgFNuBYuduS/6OzvOko8pGJjngRUBezKUTQKQRmm0wQUy44En/x7SBM
lvKevQyPeDR6mqjRfaQbszcCgYEAul/VYLANMReFQChALxbhupfiOVjYWkYAReZv
YfKbHBExKoLZpD6Ai+Nw1iUSSuunqy4IpMknw/mJjW24H86fMPjIEcyfYB/diGkJ
N84MurFupDkmZLoUoL2u84qU+Jeou5mAoFSvhIszPGG8LDe+Zp+DSqsF9Aq9vwMa
A3G+KBECgYAoa6FySIK+1MI023hXLXrHvD7RSr6bROYAs2QFXPU84ctLva1gUled
zX+QJXy0bAMmzBPftzQGsSiwbIzVbKxwy8g8PvaAiRjmEOGshcal+F5Gx4Wsw+Ez
R72PxhrjeaQmhjmSiRCGpwlUws1NR/ubZDZy/HrX0RauM6/bdxDI7wKBgQCEgoav
i/yVHuf6yaN414f+puaNZ4HMDWE8Ua53sYpe1kpis04S3O2AiGE9oHX1Fr/LkZtL
rkm7qLwH9i6nTr0YkImPPjFCouVbi3KmXrXmNyk3UfreOv9XmgW92pY4eXvahjVR
yWRRlLcFA2hK+AdD573tZNOCw/BM0uO39zMAQQKBgQCgjldpDFXaOqMl7oyLJefF
61qduyNVm4A8BR6KqCWEr/lDZk8DUWsFeEWIldqv+r30fvuZNrtZqYeuPd+isbck
G5FIV3oJz/KoM06qEAQNbaOvpTe4DbSS8xWpL2FkR9PHJ9Z72qXX1653fs7uULdP
X4zK8cpz6J/R8OrZxss30A==
-----END PRIVATE KEY-----"""
client_email = "audit-dashboard-streamlit@decisive-design-450510-k3.iam.gserviceaccount.com"
client_id = "108666738248039384753"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/audit-dashboard-streamlit%40decisive-design-450510-k3.iam.gserviceaccount.com"
